// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgvhnnpoaoeywdfvdjsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRndmhubnBvYW9leXdkZnZkanNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjM5MjgsImV4cCI6MjA1OTc5OTkyOH0.9QLmjk87g3k5B4LNTsVGfegNAxZrF2WXdPnpMJiWcxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);